### ISSUE TITLE
Не нужный if

### ISSUE THREAD

**Issue by aberezkin** [chudomozg/drom_test#1]
В этом if стейтменте нет необходимости ведь если `Object.keys(dateTime).length === 0` тогда цикл ниже не отработает ни одной итерации, что эквивалентно.

https://github.com/chudomozg/drom_test/blob/2ca596eaef9e77c9a53583eff68fde107d6833b3/src/reducers/filter.js#L5

**Comment by chudomozg** [comment]
Спасибо, внес изменения в коммите 
https://github.com/chudomozg/drom_test/commit/62ff82008ef015f1413763ef557e5b57f6d8f2f6
