### ISSUE TITLE
Можно использовать spread оператор

### ISSUE THREAD

**Issue by aberezkin** [chudomozg/drom_test#10]
https://github.com/chudomozg/drom_test/blob/2ca596eaef9e77c9a53583eff68fde107d6833b3/src/reducers/root.js#L38

`{...state, ...getPhoneValidationState(...)}`

**Comment by chudomozg** [comment]
Можно, насколько я знаю, на скорость выполнения это не влияет. т.е. выбор оператора обуславливается тем, как принято в команде. Я еще не знаю какие правила оформления кода у вас в команде. Object.assign использовался в примерах документации, поэтому я и оставил все на нем. Но соглашусь, что оператор расширения более читабелен.

**Comment by aberezkin** [comment]
> на скорость выполнения это не влияет
Да,  это буквально то же самое. Просто синтаксический сахар для функции `Object.assign`.
