### ISSUE TITLE
Синхронизация состояния

### ISSUE THREAD

**Issue by aberezkin** [chudomozg/drom_test#11]
Это похоже те "зависимости" о которых было написано в одном из комментариев. То что тут происходит это в сущности синхронизация состояний в нескольких местах. На самом деле это же состояния можно в любой момент получить с помощью `getAppStateFromValidState` в любом месте, где оно может понадобиться. То что оно синхронизируется, приводит к усложнению архитектуры.

https://github.com/chudomozg/drom_test/blob/2ca596eaef9e77c9a53583eff68fde107d6833b3/src/reducers/validate.js#L38

**Comment by chudomozg** [comment]
т.е. лучше, вообще не хранить это состояние, а вычислять его каждый раз?

**Comment by aberezkin** [comment]
Да, это делается чтобы был единый источник истины в приложении. Потому что синхронизация нескольких кусков состояния часто не тривиально и приводит к багам, при изменении кода, потому что другие разработчики (или те же самые разработчики после месяца-двух) могут не знать/забыть, что с чем нужно синхронизировать. [Вот статья на эту тему](https://kentcdodds.com/blog/dont-sync-state-derive-it).

**Comment by chudomozg** [comment]
Разобрался 
Исправил тут 27fbe5f9530d3631805c1317e18e73c68d5ae147
