### ISSUE TITLE
Использование функции перед ее определение

### ISSUE THREAD

**Issue by aberezkin** [chudomozg/drom_test#12]
Эта функция используется множество раз перед ее определением. Это сбивает с толку.

https://github.com/chudomozg/drom_test/blob/2ca596eaef9e77c9a53583eff68fde107d6833b3/src/reducers/validate.js#L69

**Comment by chudomozg** [comment]
Читал, что это устанавливается в команде, а определение после не является дурным тоном. 
Но если на практике, чаще объявляют перед использованием, буду делать так. 
Исправил https://github.com/chudomozg/drom_test/commit/10c2d6d75a60213695d8a0a0bdff3275116291a0

**Comment by aberezkin** [comment]
Вообще в `strict` моде это является ошибкой

**Comment by chudomozg** [comment]
Понял, спасибо.
