### ISSUE TITLE
Функции помимо валидности возвращает еще и новое значение, что не указано в названии

### ISSUE THREAD

**Issue by aberezkin** [chudomozg/drom_test#13]
Мне кажется логичнее бы было возвращать из этих функций только состояние валидации, чтобы название полностью отражало то, чем функция занимается.

https://github.com/chudomozg/drom_test/blob/2ca596eaef9e77c9a53583eff68fde107d6833b3/src/reducers/validate.js#L64

**Comment by chudomozg** [comment]
Разобрался 
Исправил тут 27fbe5f9530d3631805c1317e18e73c68d5ae147
