### ISSUE TITLE
Объекты передаются по ссылке

### ISSUE THREAD

**Issue by aberezkin** [chudomozg/drom_test#14]
Объекты в javascript передаются в функцию по ссылке, так что в этой строке загрязняется исходный объект.

https://github.com/chudomozg/drom_test/blob/2ca596eaef9e77c9a53583eff68fde107d6833b3/src/reducers/validate.js#L74

Чтобы скопировать объект обычно пишут

`let newObject = { ...oldObject };`

**Comment by chudomozg** [comment]
Да, это серьезная ошибка. Я старался оставить ф-цию чистой и, видимо из-за неопытности, забыл, что такая запись будет изменять исходный validState. 
Исправил в https://github.com/chudomozg/drom_test/commit/c81bf0634e5ad1ee5a7e9dc55cc50dfb735c2fdb
