### ISSUE TITLE
Some

### ISSUE THREAD

**Issue by aberezkin** [chudomozg/drom_test#15]
https://github.com/chudomozg/drom_test/blob/2ca596eaef9e77c9a53583eff68fde107d6833b3/src/reducers/validate.js#L75

Здесь корректней было бы использовать
```js
let isFormInvalid = Object.values(newValidState).some(item => item !== VALIDSTATE.valid);
return isFormInvalid ? APPSTATE.invalid : APPSTATE.fild;
```

**Comment by chudomozg** [comment]
Согласен. Не знал о существовании some, спасибо. 
Добавил 5d0691052ad8b573a64c81f320d5add015129862
