### ISSUE TITLE
Action - это действие

### ISSUE THREAD

**Issue by aberezkin** [chudomozg/drom_test#16]
Action - это действие. Наименование действия обычно - глагол. `setAppState` в данном случае.

https://github.com/chudomozg/drom_test/blob/2ca596eaef9e77c9a53583eff68fde107d6833b3/src/actions/appState.js#L3

**Comment by chudomozg** [comment]
Да, и в правду, единственный экшн, который без глагола. Спасибо за внимательность.
Исправил https://github.com/chudomozg/drom_test/commit/2be5c50cce63543c0894e29b531fe883600c1444
