### ISSUE TITLE
Не консистентный нейминг

### ISSUE THREAD

**Issue by aberezkin** [chudomozg/drom_test#2]
Имя `APPSTATE` ни о чем не говорит читателю, т.к. любая часть состояния приложения является `APPSTATE`. Почему это `APPSTATE` а остальное не `APPSTATE`?

Во всех остальных местах слова разделяются андерскором `_` а здесь нет, разнообразие заставляет думать что эта переменная в чем то особенная, хотя это не так.

Названия ключей этого объекта используют не конвенциональные сокращения, никто кроме автора кода не разберет, во что они расшифровываются.

https://github.com/chudomozg/drom_test/blob/2ca596eaef9e77c9a53583eff68fde107d6833b3/src/initStore.js#L6

**Comment by aberezkin** [comment]
Эти константы экспортятся и не являются частью инициализации стора, но находятся в файле `initStore.js`. Я бы ожидал их увидеть в каком нибудь отдельном файле, что-то типа `constants.js` или какое-то более конкретное название.

**Comment by chudomozg** [comment]
Спасибо, внес изменения в коммите 
https://github.com/chudomozg/drom_test/commit/62ff82008ef015f1413763ef557e5b57f6d8f2f6
