### ISSUE TITLE
Функциональные компоненты

### ISSUE THREAD

**Issue by aberezkin** [chudomozg/drom_test#21]
В `react` есть функциональные компоненты. Они обычно выглядят куда менее громоздкими чем классовые компоненты. В данном конкретном случае функцию `render` можно использовать как функциональный компонент.
 
https://github.com/chudomozg/drom_test/blob/62ff82008ef015f1413763ef557e5b57f6d8f2f6/src/components/Header/Title.js#L5

**Comment by chudomozg** [comment]
Да, я согласен, что ф-циональные компоненты выглядят менее громоздкими, но исходя из недостатка опыта, я не знал, если используются классы, принято ли использовать только классы или можно использовать оба вида, и это не будет дурным тоном. Поэтому написал все на классах. 
Исправил тут https://github.com/chudomozg/drom_test/commit/1df5741a6df3b52b63825e11141471335f0dd88b

**Comment by aberezkin** [comment]
Вообще, возможно классовые компоненты в принципе вскоре станут дурным тоном.
