### ISSUE TITLE
Именованные константы

### ISSUE THREAD

**Issue by aberezkin** [chudomozg/drom_test#22]
`"LOADING"` лучше вынести в именованную константу, так как это [magic string](https://softwareengineering.stackexchange.com/questions/365339/what-is-wrong-with-magic-strings).

https://github.com/chudomozg/drom_test/blob/62ff82008ef015f1413763ef557e5b57f6d8f2f6/src/components/Header/Header.js#L16

**Comment by chudomozg** [comment]
Да, это единственное место где не была использована константа. Наверняка эта строчка осталась с самой первой версии приложения, и я пропустил ее.  
Спасибо, исправил.
https://github.com/chudomozg/drom_test/commit/8792b0f6cac4b353408ef324eceedd7d727cbb84
