### ISSUE TITLE
legacy substr

### ISSUE THREAD

**Issue by aberezkin** [chudomozg/drom_test#23]
https://github.com/chudomozg/drom_test/blob/62ff82008ef015f1413763ef557e5b57f6d8f2f6/src/components/CityServices/PhoneList.js#L12
![image](https://user-images.githubusercontent.com/3759233/70235185-21f9f880-17ae-11ea-91fe-c7ad919c4dc8.png)

**Comment by chudomozg** [comment]
Знал, что он описан не непосредственно в спецификации, а в Annex , но что он уже legacy не знал.
Спасибо, буду избегать.
Исправил
