### ISSUE TITLE
Decostruction

### ISSUE THREAD

**Issue by aberezkin** [chudomozg/drom_test#24]
https://github.com/chudomozg/drom_test/blob/62ff82008ef015f1413763ef557e5b57f6d8f2f6/src/components/CityServices/ServicesContent.js#L19

Можно написать как 

```
    const { address, phones, price: cost } = this.props.city.address;
```

Ну и зачем переименовывать `price` в `cost` не совсем понятно.

**Comment by chudomozg** [comment]
` const { address, phones, price: cost } = this.props.city.address;`
Ну только без 
> .address

Смысл понятен, думаю со временем деструктуризация войдет в привычку. Еще не совсем привык ко всему "сахару". 

Про price не знаю =D не заметил

Исправил https://github.com/chudomozg/drom_test/commit/7d4147b283c7ed5df1fb859c3f30e9829ad9b9ff

**Comment by aberezkin** [comment]
Да,  `.address` скопипастил просто.
