### ISSUE TITLE
Unshift O(n)

### ISSUE THREAD

**Issue by aberezkin** [chudomozg/drom_test#25]
Эта функция работает за линейное время от длинны массива, лучше ее не использовать, там где можно не использовать.

https://github.com/chudomozg/drom_test/blob/62ff82008ef015f1413763ef557e5b57f6d8f2f6/src/components/OrderForm/OrderDate.js#L87

**Comment by chudomozg** [comment]
Да, я знал, что она медленная, хотел переписать при рефакторинге, видимо тоже забыл. 
Спасибо. 
Исправил ebed00170f85ea575b2ea989547509e79784d902
