### ISSUE TITLE
Вложенные тернарнарные выражения очень сильно усложняют код

### ISSUE THREAD

**Issue by aberezkin** [chudomozg/drom_test#27]
https://github.com/chudomozg/drom_test/blob/62ff82008ef015f1413763ef557e5b57f6d8f2f6/src/components/OrderForm/OrderForm.js#L64

**Comment by chudomozg** [comment]
Понял, буду избегать. 
Исправил https://github.com/chudomozg/drom_test/commit/d0628d80b3a87a63f7c709e79b0fc2e6eb95c096
