### ISSUE TITLE
Невидимые блоки можно не отрисовывать

### ISSUE THREAD

**Issue by aberezkin** [chudomozg/drom_test#28]
https://github.com/chudomozg/drom_test/blob/62ff82008ef015f1413763ef557e5b57f6d8f2f6/src/components/OrderForm/OrderName.js#L25

Делается это так

```jsx
{this.props.validState == VALIDSTATE.invalid && (
    <div className="order-name__fail">
         {"Пожалуйста, укажите имя"}
    </div>
)}
```

**Comment by chudomozg** [comment]
Спасибо, крутой трюк, возьму на вооружение.
Добавил https://github.com/chudomozg/drom_test/commit/c8021dd1e3459e2e45dccd7455fe1eb32a9e0635

**Comment by chudomozg** [comment]
Сократил количество кода и упростил иерархию css файлов.
