### ISSUE TITLE
Здесь корректнее использовать onChange

### ISSUE THREAD

**Issue by aberezkin** [chudomozg/drom_test#29]
https://github.com/chudomozg/drom_test/blob/62ff82008ef015f1413763ef557e5b57f6d8f2f6/src/components/OrderForm/OrderTime.js#L45

**Comment by chudomozg** [comment]
В ТЗ было сказано по OnBlur
![image](https://user-images.githubusercontent.com/52721829/70237063-02fd6580-17b2-11ea-8eb3-a4236c63e13b.png)

**Comment by aberezkin** [comment]
Да, но в ТЗ написано про валидацию. Здесь же помимо валидации, но под видом валидации устанавливается текущее значение `currentTime` в `store`. Это плохо делать в `onBlur` потому что в момент `onChange` но перед `onBlur` происходит расхождение состояния приложения с тем что показано на экране.

**Comment by chudomozg** [comment]
Т.е. Правильнее сделать это двумя разными экшнами, установку currentTime повесить на onChange, а валидацию оставить на onBlur?

**Comment by aberezkin** [comment]
Иногда конечно имеет смысл поставить изменение значения на `onBlur`, но чаще всего в этом нет необходимости. Так что да.

**Comment by chudomozg** [comment]
Поправил для инпутов и селектов
1dae8bb6539052fd4d202c471787925278fd8a6d
