### ISSUE TITLE
reducers/filter.js не содержит редюсера

### ISSUE THREAD

**Issue by aberezkin** [chudomozg/drom_test#3]
Ожидал увидеть в этом файле редюсер, так как он находится в дериктории reducers, но тут оказались хелперы.

https://github.com/chudomozg/drom_test/blob/2ca596eaef9e77c9a53583eff68fde107d6833b3/src/reducers/filter.js#L1

**Comment by chudomozg** [comment]
Не знаю, как обычно называют каталог хелперов. Перенес в helpers, думаю логично =) 
656c20d860d15d3eb84de4e2ac5a34d2b2426bf7
