### ISSUE TITLE
Нет необходимости использовать {}

### ISSUE THREAD

**Issue by aberezkin** [chudomozg/drom_test#32]
https://github.com/chudomozg/drom_test/blob/62ff82008ef015f1413763ef557e5b57f6d8f2f6/src/components/ScheduleTable.js#L53

Можно писать
```
              <th>ID</th>
              <th>Город</th>
              <th>Дата и время</th>
              <th>Имя и телефон</th>
```

**Comment by chudomozg** [comment]
Спасибо, буду знать. 
Исправил https://github.com/chudomozg/drom_test/commit/d61f1fa3057c41fbb6e610dc4ee8cacaadc8f54d
