### ISSUE TITLE
filter и some

### ISSUE THREAD

**Issue by aberezkin** [chudomozg/drom_test#4]
По факту здесь делается фильтр массива. Почти то же самое сделано в `getFiltredTimeList` но с помощью функции `filter`.

https://github.com/chudomozg/drom_test/blob/2ca596eaef9e77c9a53583eff68fde107d6833b3/src/reducers/filter.js#L7

Здесь это можно реализовать как 
```
let filtredDateTimeObj = 
  Object
    .entries(dateTime)
    .filter(([key, day]) => Object.values(day).some(time => !time.is_not_free))
    .reduce((a, [key, day]) => ({ ...a, [key]: day }), {});
```

Еще, почему то сначала `filtredDateTimeObj` инициализируется как массив а потом используется как объект, так не должно быть.

**Comment by chudomozg** [comment]
Я думал про решение с использованием цепочки методов массивов, но не смог придумать за пару часов, решил не останавливаться на долго. Потом оставил как есть. Не придумал, возможно из-за того, что я не знал про существование some.
Для меня немного сложно читать такого рода решение, долго понимал, что написано, но думаю это вопрос опыта. 
Добавил решение: 58af64d9516372ba162618279c399cea309f2679
